In [16]:
# source:
#
# http://www.randalolson.com/2016/05/08/tpot-a-python-tool-for-automating-data-science/
#
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score

In [10]:
hill_valley_data = pd.read_csv('https://raw.githubusercontent.com/rhiever/Data-Analysis-and-Machine-Learning-Projects/master/tpot-demo/Hill_Valley_without_noise.csv.gz',
                               sep='\t', compression='gzip')

In [11]:
hill_valley_data.describe()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X92,X93,X94,X95,X96,X97,X98,X99,X100,class
count,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,...,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000
mean,8200.620175,8198.880279,8196.814323,8194.363857,8191.460845,8188.026390,8183.969409,8179.185301,8173.554677,8166.942274,...,8213.918472,8213.037014,8212.330277,8211.765102,8211.314346,8210.955853,8210.671578,8210.446863,8210.269827,0.504950
std,19445.480261,19438.810247,19430.885734,19421.516432,19410.509882,19397.690861,19382.935452,19366.228647,19347.759274,19328.073898,...,19526.269248,19516.025725,19508.120434,19501.977551,19497.175707,19493.403072,19490.426387,19488.069389,19486.197641,0.500182
min,0.912984,0.914413,0.914413,0.914413,0.914414,0.914414,0.914414,0.914415,0.914415,0.914416,...,0.901746,0.901746,0.901746,0.901746,0.901746,0.901746,0.901746,0.901746,0.901746,0.000000
25%,15.952101,15.952386,15.953834,15.984956,16.083760,16.210617,16.206000,16.211379,16.250566,16.185112,...,16.223179,16.231534,16.231539,16.231543,16.231546,16.231548,16.231550,16.231552,16.188364,0.000000
50%,265.301068,265.301082,265.301099,264.657578,264.307421,264.307458,264.307504,264.307563,264.307638,264.307734,...,264.244626,264.251841,264.264955,264.274974,264.282628,264.288474,264.292938,264.296345,264.298946,1.000000
75%,4026.890054,4032.877236,4040.667379,4050.069017,4062.125508,4077.854338,4082.127063,4075.142161,4066.314821,4055.159043,...,3993.041668,4056.047526,4054.851952,4027.105652,3993.041422,3993.041383,3993.041350,3993.041322,3993.041299,1.000000
max,119604.640900,119604.643800,119604.647300,119604.651500,119604.656700,119604.662800,119604.670300,119604.679400,119604.690300,119604.703600,...,124196.019500,123402.735400,122746.512100,122203.668600,121754.615700,121383.148400,121075.862000,120821.667400,120611.391600,1.000000

In [12]:
hill_valley_data.sample(1)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X92,X93,X94,X95,X96,X97,X98,X99,X100,class
1193,15251.41702,15277.75623,15311.70957,15355.47817,15411.8994,15484.63091,15578.38767,15699.24767,15855.04592,16055.88239,...,15160.3033,15160.30329,15160.30329,15160.30328,15160.30327,15160.30327,15160.30327,15160.30326,15160.30326,1

In [13]:
cv_scores = cross_val_score(RandomForestClassifier(n_estimators=10,
                                                   n_jobs=-1),
                            X=hill_valley_data.drop('class',axis=1).values,
                            y=hill_valley_data.loc[:, 'class'].values,
                            cv=10)
print(cv_scores)

print(np.mean(cv_scores))

[ 0.56557377  0.6147541   0.5785124   0.56198347  0.65289256  0.57024793
  0.67768595  0.50413223  0.55371901  0.61983471]
0.589933613332

In [14]:
cv_scores = cross_val_score(RandomForestClassifier(n_estimators=100,
                                                   n_jobs=-1),
                            X=hill_valley_data.drop('class',axis=1).values,
                            y=hill_valley_data.loc[:, 'class'].values,
                            cv=10)
print(cv_scores)

print(np.mean(cv_scores))

[ 0.60655738  0.60655738  0.5785124   0.60330579  0.65289256  0.62809917
  0.66942149  0.56198347  0.51239669  0.63636364]
0.605608996071

In [17]:
from sklearn.linear_model import LogisticRegression

cv_scores = cross_val_score(LogisticRegression(),
                            X=hill_valley_data.drop('class',axis=1).values,
                            y=hill_valley_data.loc[:, 'class'].values,
                            cv=10)
print(cv_scores)

print(np.mean(cv_scores))

[ 1.          1.          1.          0.99173554  1.          1.
  0.99173554  1.          1.          1.        ]
0.998347107438

In [18]:
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline

hill_valley_noisy_data = pd.read_csv('https://raw.githubusercontent.com/rhiever/Data-Analysis-and-Machine-Learning-Projects/master/tpot-demo/Hill_Valley_with_noise.csv.gz', 
                                     sep='\t', 
                                     compression='gzip')

In [19]:
hill_valley_noisy_data.describe()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X92,X93,X94,X95,X96,X97,X98,X99,X100,class
count,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,...,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000
mean,8169.091881,8144.306262,8192.653738,8176.868738,8128.297211,8173.030008,8188.582748,8183.641543,8154.670066,8120.767574,...,8120.056815,8125.917409,8158.793812,8140.885421,8213.480611,8185.594002,8140.195355,8192.960891,8156.197376,0.500000
std,17974.950461,17881.049734,18087.938901,17991.903982,17846.757963,17927.114105,18029.562695,18048.582159,17982.390713,17900.798206,...,17773.190621,17758.182403,17919.510371,17817.945646,18016.445265,17956.084223,17768.356106,18064.781479,17829.310973,0.500206
min,0.920000,0.900000,0.850000,0.890000,0.880000,0.860000,0.870000,0.650000,0.650000,0.620000,...,0.870000,0.900000,0.870000,0.880000,0.890000,0.890000,0.860000,0.910000,0.890000,0.000000
25%,19.602500,19.595000,18.925000,19.277500,19.210000,19.582500,18.690000,19.062500,19.532500,19.285000,...,19.197500,18.895000,19.237500,19.385000,19.027500,19.135000,19.205000,18.812500,19.145000,0.000000
50%,301.425000,295.205000,297.260000,299.720000,295.115000,294.380000,295.935000,290.850000,294.565000,295.160000,...,297.845000,295.420000,299.155000,293.355000,301.370000,296.960000,300.925000,299.200000,302.275000,0.500000
75%,5358.795000,5417.847500,5393.367500,5388.482500,5321.987500,5328.040000,5443.977500,5283.655000,5378.180000,5319.097500,...,5355.355000,5386.037500,5286.385000,5345.797500,5300.890000,5361.047500,5390.850000,5288.712500,5357.847500,1.000000
max,117807.870000,108896.480000,119031.350000,110212.590000,113000.470000,116848.390000,115609.240000,118522.320000,112895.900000,117798.300000,...,113858.680000,112948.830000,112409.570000,112933.730000,112037.220000,115110.420000,116431.960000,113291.960000,114533.760000,1.000000

In [20]:
hill_valley_noisy_data.sample(1)

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X92,X93,X94,X95,X96,X97,X98,X99,X100,class
639,197.4,218.55,216.97,219.04,220.08,192.74,203.73,218.83,196.7,214.04,...,210.28,198.37,214.32,195.24,212.4,215.26,207.8,190.38,193.67,0

In [21]:
cv_scores = cross_val_score(RandomForestClassifier(n_estimators=100, n_jobs=-1),  
                            X=hill_valley_noisy_data.drop('class', axis=1).values,  
                            y=hill_valley_noisy_data.loc[:, 'class'].values,  
                            cv=10)
print(cv_scores)

print(np.mean(cv_scores))

[ 0.53278689  0.54098361  0.48360656  0.62295082  0.6147541   0.53278689
  0.58333333  0.59166667  0.625       0.55833333]
0.568620218579

In [22]:
cv_scores = cross_val_score(make_pipeline(PCA(n_components=10),  
                                          RandomForestClassifier(n_estimators=100,  
                                                                 n_jobs=-1)),  
                            X=hill_valley_noisy_data.drop('class', axis=1).values,  
                            y=hill_valley_noisy_data.loc[:, 'class'].values,  
                            cv=10)
print(cv_scores)

print(np.mean(cv_scores))

[ 0.95901639  0.98360656  0.87704918  0.96721311  0.94262295  0.92622951
  0.925       0.93333333  0.94166667  0.96666667]
0.942240437158